server:
  port: 8086

heartrate:
  api:
    url: http://localhost:8081/api/heartrate

spring:
  rabbitmq:
    host: leopard.lmq.cloudamqp.com
    port: 5671
    username: eenxeqeq
    password: lC6oGNvjYq1wuP_H6sLv5d8fFwjZcvXR
    virtual-host: eenxeqeq
    ssl:
      enabled: true
    connection-timeout: 10000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

logging:
  level:
    com.monitoring: DEBUG
    org.springframework.amqp: DEBUG