server:
  port: 8087

bloodpressure:
  api:
    url: http://localhost:8082/api/bloodpressure

monitoring:
  api:
    url: http://localhost:8080/api/monitoring

spring:
  application:
    name: BloodPressureService

  rabbitmq:
    host: leopard.lmq.cloudamqp.com
    port: 5671
    username: eenxeqeq
    password: lC6oGNvjYq1wuP_H6sLv5d8fFwjZcvXR
    virtual-host: eenxeqeq
    ssl:
      enabled: true
    connection-timeout: 30000
    requested-heartbeat: 30
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 2
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 10
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 5
          max-interval: 10000
          multiplier: 2

logging:
  level:
    com.monitoring: INFO
    org.springframework.amqp: WARN
    org.springframework.web.reactive: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"